/** Motor común de mazos. La IA NO participa en la extracción. */
const MAJORS=['El Loco','El Mago','La Sacerdotisa','La Emperatriz','El Emperador','El Hierofante','Los Enamorados','El Carro','La Fuerza','El Ermitaño','La Rueda de la Fortuna','La Justicia','El Colgado','La Muerte','La Templanza','El Diablo','La Torre','La Estrella','La Luna','El Sol','El Juicio','El Mundo'];
const NUMS=['As','Dos','Tres','Cuatro','Cinco','Seis','Siete','Ocho','Nueve','Diez','Sota','Caballero','Reina','Rey'];
const SUITS={Bastos:['acción, deseo, iniciativa','agotamiento, impulsividad, bloqueo'],Copas:['emoción, vínculo, apertura','sensibilidad desbordada, apego, cierre emocional'],Espadas:['mente, conversación, decisiones','rumiación, conflicto, confusión'],Oros:['estabilidad, realidad, recursos','inseguridad material, rigidez, desequilibrio'],Flechas:['deseo, comunicación, dirección','palabras hirientes, ansiedad, bloqueo'],Monedas:['seguridad, realidad, cuidado','inseguridad, apego material, desequilibrio']};
const NUM_MEANINGS={As:['inicio, potencial','potencial bloqueado'],Dos:['elección, equilibrio','indecisión, desequilibrio'],Tres:['crecimiento, expresión','dispersión, demora'],Cuatro:['estructura, pausa','estancamiento, rigidez'],Cinco:['tensión, aprendizaje','conflicto prolongado'],Seis:['avance, armonización','dependencia del pasado'],Siete:['evaluación, estrategia','dudas, desgaste'],Ocho:['movimiento, disciplina','restricción, exceso'],Nueve:['madurez, perseverancia','cansancio, defensividad'],Diez:['culminación, carga','sobrecarga, cierre pendiente'],Sota:['curiosidad, mensaje','inmadurez, mensaje confuso'],Caballero:['movimiento, búsqueda','impulsividad, dispersión'],Reina:['madurez receptiva','control o exceso'],Rey:['dominio, responsabilidad','rigidez o abuso de poder']};
const DECK_CONFIG={riderWaite:{name:'Rider-Waite',suits:['Bastos','Copas','Espadas','Oros'],reversed:true,spread:'celtic',count:10},tarotMitico:{name:'Tarot Mítico',suits:['Bastos','Copas','Espadas','Oros'],reversed:false,spread:'celtic',count:10},loversPath:{name:'Lover’s Path',suits:['Staves','Cups','Arrows','Coins'],reversed:true,spread:'love',count:13}};
const CELTIC_POSITIONS=['Situación actual','Desafío o influencia','Base o raíz','Pasado reciente','Meta o conciencia','Futuro cercano','Actitud o mundo interior','Entorno e influencias externas','Esperanzas y temores','Resultado o tendencia'];
const LOVE_POSITIONS=['Tu energía','Su energía','Lo que los une','Lo que los separa','Lo que sientes','Lo que siente','Lo que deseas','Lo que desea','Lo que no se dice','La influencia del pasado','El aprendizaje','La tendencia','Consejo para el amor'];
function buildDeck(id){const cfg=DECK_CONFIG[id];const cards=[];MAJORS.forEach((name,i)=>cards.push({id:`${id}-major-${i}`,name,arcana:'mayor',number:i,upright:`${name}: significado principal`,reversed:`${name}: significado invertido`}));cfg.suits.forEach(s=>NUMS.forEach((n,i)=>{const m=NUM_MEANINGS[n],sm=SUITS[s];cards.push({id:`${id}-${s.toLowerCase()}-${i+1}`,name:`${n} de ${s}`,arcana:'menor',suit:s,upright:`${sm[0]}; ${m[0]}`,reversed:`${sm[1]}; ${m[1]}`})}));return{id,name:cfg.name,suits:cfg.suits,cards,total:cards.length,reversed:cfg.reversed,spread:cfg.spread,count:cfg.count}}
const DECKS=Object.fromEntries(Object.keys(DECK_CONFIG).map(buildDeck));
function draw(deckId){const deck=DECKS[deckId];if(!deck)throw Error('Mazo no encontrado');const positions=deck.spread==='love'?LOVE_POSITIONS:CELTIC_POSITIONS;const pool=[...deck.cards];return{deckId,deck:deck.name,spread:deck.spread==='love'?'Tirada del Amor':'Cruz Celta',cards:positions.map((position,i)=>{const card=pool.splice(Math.floor(Math.random()*pool.length),1)[0];const orientation=deck.reversed&&(Math.random()<.5)?'invertida':'derecha';return{position:i+1,positionName:position,cardId:card.id,card:card.name,orientation,meaning:orientation==='derecha'?card.upright:card.reversed}}),createdAt:new Date().toISOString()}}
function validateReading(r){if(!r||r.cards?.length!==DECKS[r.deckId]?.count)return{ok:false,error:'Cantidad de cartas incorrecta'};if(new Set(r.cards.map(c=>c.cardId)).size!==r.cards.length)return{ok:false,error:'Hay cartas repetidas'};if(!DECKS[r.deckId].reversed&&r.cards.some(c=>c.orientation==='invertida'))return{ok:false,error:'Este mazo no admite invertidas'};return{ok:true}}
if(typeof module!=='undefined')module.exports={DECKS,CELTIC_POSITIONS,LOVE_POSITIONS,draw,validateReading};
