/** Biblioteca común para los 3 mazos. La IA no participa en la extracción. */
const MAJORS=[
['El Loco','inicio, libertad, apertura','impulsividad, falta de dirección, riesgo'],['El Mago','iniciativa, recursos, comunicación','dispersión, manipulación, bloqueo'],['La Sacerdotisa','intuición, silencio, profundidad','secretos, desconexión, pasividad'],['La Emperatriz','afecto, creación, abundancia','dependencia, exceso, estancamiento'],['El Emperador','estructura, estabilidad, límites','rigidez, control, autoritarismo'],['El Hierofante','valores, compromiso, aprendizaje','convenciones, dogma, resistencia'],['Los Enamorados','elección, vínculo, coherencia','duda, conflicto de valores, distancia'],['El Carro','avance, decisión, dirección','impulsividad, falta de control, demora'],['La Fuerza','calma, valentía, dominio interior','inseguridad, tensión, desgaste'],['El Ermitaño','reflexión, búsqueda, prudencia','aislamiento, evasión, cierre'],['La Rueda de la Fortuna','cambio, ciclo, oportunidad','resistencia, inestabilidad, repetición'],['La Justicia','equilibrio, verdad, responsabilidad','desbalance, evasión, juicio severo'],['El Colgado','pausa, nueva mirada, entrega','bloqueo, sacrificio estéril, demora'],['La Muerte','cierre, transformación, renovación','resistencia, apego, transición difícil'],['La Templanza','armonía, integración, paciencia','exceso, desorden, impaciencia'],['El Diablo','deseo, intensidad, apego','dependencia, liberación, límites'],['La Torre','revelación, ruptura, cambio brusco','resistencia, tensión acumulada, demora'],['La Estrella','esperanza, autenticidad, confianza','desánimo, duda, idealización'],['La Luna','sensibilidad, intuición, incertidumbre','confusión, miedo, claridad emergente'],['El Sol','claridad, alegría, vitalidad','exposición, cansancio, optimismo forzado'],['El Juicio','despertar, decisión, revisión','culpa, postergación, dificultad para cerrar'],['El Mundo','culminación, integración, plenitud','ciclo incompleto, dispersión, falta de cierre']
];
const NUMS=['As','Dos','Tres','Cuatro','Cinco','Seis','Siete','Ocho','Nueve','Diez','Sota','Caballero','Reina','Rey'];
const NUM_MEANINGS={As:['inicio, potencial','potencial bloqueado'],Dos:['elección, equilibrio','indecisión, desequilibrio'],Tres:['crecimiento, expresión','dispersión, demora'],Cuatro:['estructura, pausa','estancamiento, rigidez'],Cinco:['tensión, aprendizaje','conflicto prolongado'],Seis:['avance, armonización','dependencia del pasado'],Siete:['evaluación, estrategia','dudas, desgaste'],Ocho:['movimiento, disciplina','restricción, exceso'],Nueve:['madurez, perseverancia','cansancio, defensividad'],Diez:['culminación, carga','sobrecarga, cierre pendiente'],Sota:['curiosidad, mensaje','inmadurez, mensaje confuso'],Caballero:['movimiento, búsqueda','impulsividad, dispersión'],Reina:['madurez receptiva','control o exceso'],Rey:['dominio, responsabilidad','rigidez o abuso de poder']};
const SUITS={Bastos:['acción, deseo, iniciativa','agotamiento, impulsividad, bloqueo'],Copas:['emoción, vínculo, apertura','sensibilidad desbordada, apego, cierre emocional'],Espadas:['mente, conversación, decisiones','rumiación, conflicto, confusión'],Oros:['estabilidad, realidad, recursos','inseguridad material, rigidez, desequilibrio'],Flechas:['deseo, comunicación, dirección','palabras hirientes, ansiedad, bloqueo'],Monedas:['seguridad, realidad, cuidado','inseguridad, apego material, desequilibrio']};
const DECK_CONFIG={riderWaite:{name:'Rider-Waite',suits:['Bastos','Copas','Espadas','Oros']},loversPath:{name:"Lover's Path",suits:['Bastos','Copas','Flechas','Monedas']},tarotMitico:{name:'Tarot Mítico',suits:['Bastos','Copas','Espadas','Oros']}};
const POSITIONS=['Situación actual','Desafío o influencia','Base o raíz','Pasado reciente','Meta o conciencia','Futuro cercano','Actitud o mundo interior','Entorno e influencias externas','Esperanzas y temores','Resultado o tendencia'];
function buildDeck(id){const cfg=DECK_CONFIG[id];const cards=[];MAJORS.forEach((m,i)=>cards.push({id:`${id}-major-${i}`,name:m[0],arcana:'mayor',number:i,upright:m[1],reversed:m[2]}));cfg.suits.forEach(s=>NUMS.forEach((n,i)=>{const m=NUM_MEANINGS[n];const sm=SUITS[s];cards.push({id:`${id}-${s.toLowerCase()}-${i+1}`,name:`${n} de ${s}`,arcana:'menor',suit:s,upright:`${sm[0]}; ${m[0]}`,reversed:`${sm[1]}; ${m[1]}`})}));return{id,name:cfg.name,suits:cfg.suits,cards,total:cards.length}}
const DECKS=Object.fromEntries(Object.keys(DECK_CONFIG).map(buildDeck));
function drawCeltic(deckId){const deck=DECKS[deckId];if(!deck)throw Error('Mazo no encontrado');const pool=[...deck.cards];const cards=POSITIONS.map((position,i)=>{const index=Math.floor(Math.random()*pool.length);const card=pool.splice(index,1)[0];const orientation=Math.random()<.5?'derecha':'invertida';return{position:i+1,positionName:position,cardId:card.id,card:card.name,orientation,meaning:orientation==='derecha'?card.upright:card.reversed}});return{deckId,deck:deck.name,spread:'Cruz Celta',cards,createdAt:new Date().toISOString()}}
function validateReading(r){if(!r||r.cards?.length!==10)return{ok:false,error:'La tirada debe tener 10 cartas'};if(new Set(r.cards.map(c=>c.cardId)).size!==10)return{ok:false,error:'Hay cartas repetidas'};return{ok:true}}
if(typeof module!=='undefined')module.exports={DECKS,POSITIONS,drawCeltic,validateReading};
